### PR TITLE
PDA-72 Summary API

### PR DESCRIPTION
**Pull request by ffleandro**

### CODE REVIEW

**Comment by ffleandro** [comment]
This PR basically renames the concept of a Summary Data Type to a Summary Data Repository;

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by joewhite101 — APPROVED** [review]
Looks good.

**Comment by joewhite101** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
