### PR TITLE
PDA-64 Process Form Widget

### PR DESCRIPTION
**Pull request by jeffgo10**
- Process Form using json-schema-form
 - unifying task completion and process form generator into one common component `JSONForm`
 - unifying context for custom events

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by gReis89** [comment]
package-lock.json is being update but there is no dependency changes here, can u check it @jeffgo10 ?

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
All is well

**Comment by jeffgo10** [comment]
> package-lock.json is being update but there is no dependency changes here, can u check it @jeffgo10 ?

Sorry @gReis89, this must have been included during my merge from master. Should be fine now. pls verify when you can

**Review by gReis89 — APPROVED** [review]
looking good!

**Review by gReis89 — APPROVED** [review]

**Pull request merged**
