### PR TITLE
PDA-89 Keycloak on pda widgets

### PR DESCRIPTION
**Pull request by rimselis**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by rimselis** [comment]
@jeffgo10, did https://github.com/entando/entando-process-driven-plugin/pull/90 cover what is in this PR, can I close this one?

**Comment by jeffgo10** [comment]
> @jeffgo10, did #90 cover what is in this PR, can I close this one?

yes @rimselis it has been already covered. you can close this. thanks

**Pull request closed without merging**
