### PR TITLE
PDA-71 OvertimeGraph UI

### PR DESCRIPTION
**Pull request by raxkaynan**
Adds OvertimeGraph widget and OvertimeGraphConfig

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by gReis89** [comment]
hey @raxkaynan, please rebase and fix the conflicts, will merge after that.

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Review by gReis89 — APPROVED** [review]
approved

**Pull request merged**
