### PR TITLE
PDA-49 get process form

### PR DESCRIPTION
**Pull request by BrenoQVDS**
Adding new endpoint for getting the process form

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — DISMISSED** [review]

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — APPROVED** [review]

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
