### PR TITLE
PDA-78 and PDA-147: Task lifecycle operations / bulk actions

### PR DESCRIPTION
**Pull request by werbth**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — DISMISSED** [review]

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — APPROVED** [review]

**Comment by entando-service** [comment]
All is well

**Pull request merged**
