### PR TITLE
PDA-53 Process Form Json Schema

### PR DESCRIPTION
**Pull request by ffleandro**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Looks good to me. Im assuming those tests are failing because the core is not merged.

**Review by BrenoQVDS — DISMISSED** [review]
Looks good to me. Im assuming those tests are failing because the core is not merged.

**Review by werbth — DISMISSED** [review]

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by werbth** [comment]
retest this please

**Comment by entando-service** [comment]
All is well

**Review by werbth — APPROVED** [review]

**Pull request merged**
