### PR TITLE
PDA-122 additional form widgets

### PR DESCRIPTION
**Pull request by rimselis**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Review by jeffgo10 — APPROVED** [review]
looks good

**Comment by entando-service** [comment]
All is well

**Pull request merged**
