### PR TITLE
PDA-118: Support groups on task list endpoint

### PR DESCRIPTION
**Pull request by werbth**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — DISMISSED** [review]
There should be integration test case to endpoint with group and without groups

**Comment by werbth** [comment]
> There should be integration test case to endpoint with group and without groups

Same argument as here: https://github.com/entando/pda-core-engine/pull/34#issuecomment-589744086

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by BrenoQVDS** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Review by BrenoQVDS — APPROVED** [review]

**Pull request merged**
