### PR TITLE
PDA-35: List task columns

### PR DESCRIPTION
**Pull request by werbth**
Jira ticket: https://jira.entando.org/browse/PDA-35

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — DISMISSED** [review]

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by ffleandro — APPROVED** [review]

**Comment by ffleandro** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
