### PR TITLE
PDA-60 Redesign Task Model and refactored TaskService to use Kie Client Library

### PR DESCRIPTION
**Pull request by ffleandro**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Review by werbth — APPROVED** [review]

**Comment by werbth** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
